In [1]:
import pandas as pd

feature_matrix    = pd.read_parquet('../data/features/feature_matrix.parquet')
broad_daily       = pd.read_parquet('../data/features/broad_daily.parquet')
opec_flags        = pd.read_parquet('../data/features/opec_flags.parquet')
disruption_flags  = pd.read_parquet('../data/features/disruption_flags.parquet')

In [2]:
feature_matrix.head(10)

,date,close,close_pct_change,headline_count_lag1,sentiment_mean_lag1,sentiment_std_lag1,sentiment_min_lag1,sentiment_max_lag1,negative_ratio_lag1,positive_ratio_lag1,...,inventory_chg_kb_lag1,inventory_surprise_kb_lag1,production_chg_kbd_lag1,imports_chg_kbd_lag1,refinery_util_pct_lag1,refinery_util_chg_pct_lag1,usd_ret_pct_lag1,usd_mom_4w_lag1,spx_ret_pct_lag1,yield_10y_chg_lag1
0,2020-02-07,50.36,-4.422091,2.0,0.170050,0.000000,-0.5118,0.8519,0.500000,0.500000,...,3355.0,-1056.333333,-100.0,-45.0,87.4,0.2,0.154817,0.650336,-2.122611,-0.19
1,2020-02-14,50.83,0.933280,1.0,0.999700,0.000000,0.9997,0.9997,0.000000,1.000000,...,7459.0,2566.833333,100.0,363.0,88.0,0.6,0.668858,1.252219,3.168171,0.08
2,2020-02-21,53.14,4.544560,1.0,0.677600,0.000000,0.6776,0.6776,0.000000,1.000000,...,415.0,-1844.166667,0.0,-431.0,89.4,1.4,-0.074072,1.179067,1.576159,0.00
3,2020-02-28,48.36,-8.995107,0.0,0.000000,0.000000,0.0000,0.0000,0.000000,0.000000,...,452.0,-2136.833333,0.0,-330.0,87.9,-1.5,0.536839,1.290894,-1.254674,-0.13
4,2020-03-06,45.57,-5.769231,1.0,0.988300,0.000000,0.9883,0.9883,0.000000,1.000000,...,784.0,-4687.166667,100.0,21.0,86.9,-1.0,0.520730,1.660957,-11.490675,-0.33
5,2020-03-13,32.39,-28.922537,0.0,0.000000,0.000000,0.0000,0.0000,0.000000,0.000000,...,7664.0,5286.166667,-100.0,174.0,86.4,-0.5,-0.804203,0.173378,0.614375,-0.39
6,2020-03-20,24.19,-25.316456,4.0,0.747833,0.822789,-0.2500,0.9565,0.166667,0.833333,...,1954.0,-221.000000,100.0,127.0,86.4,0.0,3.194397,3.449940,-8.792647,0.20
7,2020-03-27,19.44,-19.636213,1.0,0.909100,0.000000,0.9091,0.9091,0.000000,1.000000,...,1623.0,-1156.166667,-100.0,-422.0,87.3,0.9,3.734179,6.739925,-14.979602,-0.02
8,2020-04-03,21.69,11.574074,1.0,0.936400,0.000000,0.9364,0.9364,0.000000,1.000000,...,13833.0,10992.666667,0.0,-70.0,82.3,-5.0,-2.029436,4.031981,10.262829,-0.20
9,2020-04-10,24.41,12.540341,1.0,0.843700,0.000000,0.8437,0.8437,0.000000,1.000000,...,15177.0,8338.000000,-600.0,-173.0,75.6,-6.7,1.645824,6.601457,-2.078325,-0.10

In [3]:
feature_matrix.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 255 entries, 0 to 254
Data columns (total 33 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   date                        255 non-null    datetime64[ns]
 1   close                       255 non-null    float64
 2   close_pct_change            255 non-null    float64
 3   headline_count_lag1         255 non-null    float64
 4   sentiment_mean_lag1         255 non-null    float64
 5   sentiment_std_lag1          255 non-null    float64
 6   sentiment_min_lag1          255 non-null    float64
 7   sentiment_max_lag1          255 non-null    float64
 8   negative_ratio_lag1         255 non-null    float64
 9   positive_ratio_lag1         255 non-null    float64
 10  log_headline_count_lag1     255 non-null    float64
 11  opec_event_day_lag1         255 non-null    float64
 12  opec_decision_day_lag1      255 non-null    float64
 13  opec_sentiment_lag1         255 non-null    float64
 14  disruption_event_day_lag1   255 non-null    float64
 15  disruption_intensity_lag1   255 non-null    float64
 16  realized_vol_lag1           255 non-null    float64
 17  regime_0_lag1               255 non-null    float64
 18  regime_1_lag1               255 non-null    float64
 19  regime_2_lag1               255 non-null    float64
 20  hmm_regime_0_lag1           255 non-null    float64
 21  hmm_regime_1_lag1           255 non-null    float64
 22  hmm_regime_2_lag1           255 non-null    float64
 23  inventory_chg_kb_lag1       255 non-null    float64
 24  inventory_surprise_kb_lag1  255 non-null    float64
 25  production_chg_kbd_lag1     255 non-null    float64
 26  imports_chg_kbd_lag1        255 non-null    float64
 27  refinery_util_pct_lag1      255 non-null    float64
 28  refinery_util_chg_pct_lag1  255 non-null    float64
 29  usd_ret_pct_lag1            255 non-null    float64
 30  usd_mom_4w_lag1             255 non-null    float64
 31  spx_ret_pct_lag1            255 non-null    float64
 32  yield_10y_chg_lag1          255 non-null    float64
dtypes: datetime64[ns](1), float64(32)
memory usage: 65.9 KB

In [4]:
feature_matrix.describe()

,date,close,close_pct_change,headline_count_lag1,sentiment_mean_lag1,sentiment_std_lag1,sentiment_min_lag1,sentiment_max_lag1,negative_ratio_lag1,positive_ratio_lag1,...,inventory_chg_kb_lag1,inventory_surprise_kb_lag1,production_chg_kbd_lag1,imports_chg_kbd_lag1,refinery_util_pct_lag1,refinery_util_chg_pct_lag1,usd_ret_pct_lag1,usd_mom_4w_lag1,spx_ret_pct_lag1,yield_10y_chg_lag1
count,255,255.000000,255.000000,255.000000,255.000000,255.000000,255.000000,255.000000,255.000000,255.000000,...,255.000000,255.000000,255.000000,255.000000,255.000000,255.000000,255.000000,255.000000,255.000000,255.000000
mean,2022-07-20 16:22:35.294117632,71.566392,1.516757,7.560784,0.586924,0.330413,-0.216488,0.912862,0.143802,0.777737,...,-974.596078,-697.047040,2.294118,-0.909804,87.063922,0.015686,0.045144,0.168804,0.264710,0.011098
min,2020-02-07 00:00:00,3.320000,-83.499006,0.000000,-0.983800,0.000000,-0.999900,-0.983800,0.000000,0.000000,...,-17049.000000,-13477.250000,-1500.000000,-1840.000000,56.000000,-14.500000,-2.029436,-4.039897,-14.979602,-0.400000
25%,2021-05-03 12:00:00,64.565000,-2.062613,3.000000,0.387836,0.000000,-0.940550,0.982800,0.000000,0.666667,...,-5320.500000,-4065.048611,-100.000000,-418.500000,84.950000,-0.700000,-0.516018,-0.997691,-1.238813,-0.060000
50%,2022-07-22 00:00:00,74.680000,0.683498,6.000000,0.655375,0.274640,-0.458800,0.995800,0.075000,0.833333,...,-1321.000000,-1174.111111,0.000000,-26.000000,88.800000,0.300000,0.081944,0.079186,0.476907,0.010000
75%,2023-10-09 12:00:00,82.515000,2.865212,11.000000,0.858925,0.546127,0.521150,0.998100,0.250000,1.000000,...,2160.000000,2139.611111,100.000000,364.000000,92.100000,1.100000,0.524946,1.258554,1.666505,0.100000
max,2024-12-27 00:00:00,120.430000,373.192771,30.000000,1.000000,1.384444,1.000000,1.000000,1.000000,1.000000,...,21563.000000,17045.375000,1200.000000,2003.000000,95.800000,13.000000,3.734179,6.739925,12.101742,0.340000
std,NaN,20.440220,24.736367,6.243361,0.338245,0.344680,0.747907,0.285383,0.184083,0.260817,...,6133.170607,5376.908398,238.589498,679.842579,6.776287,2.470437,0.780176,1.572010,2.804914,0.131627

In [5]:
broad_daily.head(10)

,date,headline_count,sentiment_mean,sentiment_std,sentiment_min,sentiment_max,negative_ratio,positive_ratio,log_headline_count
0,2020-01-17,1,0.9940,NaN,0.9940,0.9940,0.0,1.0,0.693147
1,2020-01-19,1,0.9988,NaN,0.9988,0.9988,0.0,1.0,0.693147
2,2020-01-30,1,-0.5118,NaN,-0.5118,-0.5118,1.0,0.0,0.693147
3,2020-01-31,1,0.8519,NaN,0.8519,0.8519,0.0,1.0,0.693147
4,2020-02-02,1,0.9997,NaN,0.9997,0.9997,0.0,1.0,0.693147
5,2020-02-11,1,0.6776,NaN,0.6776,0.6776,0.0,1.0,0.693147
6,2020-02-25,1,0.9883,NaN,0.9883,0.9883,0.0,1.0,0.693147
7,2020-03-09,1,0.9552,NaN,0.9552,0.9552,0.0,1.0,0.693147
8,2020-03-10,2,0.3318,0.822789,-0.2500,0.9136,0.5,0.5,1.098612
9,2020-03-12,1,0.9565,NaN,0.9565,0.9565,0.0,1.0,0.693147

In [6]:
opec_flags.head(10)

,date,opec_article_count,opec_sentiment,opec_event_day,opec_decision_day,opec_event_window
0,2020-02-02,1,0.99970,1,0,1
1,2020-02-20,1,0.63690,1,0,1
2,2020-02-21,1,0.95590,1,0,1
3,2020-02-25,1,0.98830,1,0,1
4,2020-03-10,1,-0.25000,1,0,1
5,2020-03-25,1,0.52330,1,0,1
6,2020-04-14,2,0.11045,1,0,1
7,2020-04-24,1,-0.96870,1,0,1
8,2020-04-27,1,0.62490,1,0,1
9,2020-05-18,1,0.96940,1,0,1

In [7]:
disruption_flags.head(10)

,date,disruption_intensity,disruption_sentiment,disruption_event_day,disruption_event_window
0,2020-02-25,1,0.9883,1,1
1,2020-09-29,1,0.8588,1,1
2,2020-10-23,1,0.9060,1,1
3,2021-01-09,1,0.9952,1,1
4,2021-01-15,1,-0.5574,1,1
5,2021-02-10,1,1.0000,1,1
6,2021-02-27,1,0.9944,1,1
7,2021-03-05,1,0.2263,1,1
8,2021-03-16,1,-0.0516,1,1
9,2021-03-24,1,0.9744,1,1